version: 2
#registries:
#  github-octocat:
#    type: git
#    url: https://github.com
#    username: x-access-token
#    # dont love this being a personal access token tied to my account
#    password: ${{secrets.LEO_GITHUB_ACCESS_TOKEN}}
updates:
- package-ecosystem: pip
  directory: "/"
  registries: "*"
  # hmmmmmmmmm i feel uncomfortable with this but think it needs this to check the github auth
  # insecure-external-code-execution: allow 
  schedule:
    # daily, weekly, monthly
    interval: "daily"
  ignore:
    # don't bump marshmallow to v3 or greater
    - dependency-name: "marshmallow"
      versions: [">=3"]
    # ignore minor version bumps for any lib. security updates overrule this.
    - dependency-name: "*"
      update-types: ["version-update:semver-minor", "version-update:semver-patch"]
  # dependabot won't open any extra if there are 5 PRs open already
  open-pull-requests-limit: 5
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "daily"
  ignore:
    # will this skip devDependencies?
    - dependency-type: "development"


## THOUGHTS. 
# i dont think we can have separate schedules for separate dependencies. we might be able to by having 
# we cant bundle up version bumps into one PR
# there's a concept of dependency groups - "Development" and "Production" at least. Not clear what exactly these are.
# will limiting update-types in ignore stop it opening PRs for minor versions of flask? (i think it will)
# should we use github comments to control dependabot (eg "@dependabot ignore this minor version")

